### ISSUE TITLE
Questions about bounce tracking rollout

### ISSUE THREAD

**Issue by brunopereira-hotmart** [privacysandbox/privacy-sandbox-dev-support#203]
We are carrying out bounce tracking tests and some doubts have arisen.
The documentation https://developers.google.com/privacy-sandbox/setup/web/chrome-facilitated-testing?hl=pt-br cites an A/B test as mode A and B. This A/B test will be applied for bounce tracking cases too?
If not, will there be a gradual rollout for bounce tracking prevention[https://developer.chrome.com/blog/bounce-tracking-mitigations-dev-trial] with A/B testing, specific headers? Or will it be applied to everyone at once?
If there are headers for deprecation, is there any documentation for testing in which we would be able to receive the header in the request for testing?

**Comment by wanderview** [comment]
Bounce tracking mitigations are [rolled out to 100% as of October](https://groups.google.com/a/chromium.org/g/blink-dev/c/Lxi7LfRyI4c/m/P-BwSJfXFAAJ).  They only take effect in situations where 3P cookies are blocked, however.  Right now that means users who have opted into 3P cookie blocking and the default cookie blocking setting in incognito mode.

As third-party cookie deprecation begins at 1% during the facilitated testing in January, bounce tracking mitigations will begin to affect more users since 3P cookies will be blocked in more cases.

**Comment by brunohenriquepj** [comment]
In the case of first-party cookies bounce tracking, is there a rollout plan or will there be a rollout only in October along with 100% of the 3P?
