### ISSUE TITLE
SAML Front Channel Logout and clearing cookies in sites on different domains

### ISSUE THREAD

**Issue by michal-tobiasz-wttech** [privacysandbox/privacy-sandbox-dev-support#273]
Currently in our project, we have sites that are on the same domain, let's say example.com. All these sites are integrated with an Identity Provider (IDP) using SAML, enabling Single Sign On (SSO) and Single Log out (SLO) mechanisms. The IDP is also on the same domain, idp.example.com. These sites use a cookie to indicate if a user is logged in. When a user logs out from one of the sites, the IDP initiates a Front Channel Logout with the other sites. It displays a page with a hidden iframe containing a SAML Logout request. In response to the SAML Logout request, we clear the cookie that was created during login at the site level.

The plan is to have sites on different domains than example.com, and then also the IDP. In the logout flow, the cookie that we want to clear will be treated as a cross-site cookie, and the browser will not allow it to be cleared. As a result, the user will be logged out from the IDP and the site where they triggered the logout, but they will still be logged into sites that have a different domain and where the clearing of cookies was blocked. For example, this would occur for site1.newexample.com.

What is your advice here? How could we clear the cookie from the site?

**Comment by johannhof** [comment]
Thanks for reaching out! It would be good if you could help me understand your setup: Do you control both the IdP and the Relying Parties (the top-level sites)?

As I understand it there is an interest in finding developers who would be interested in trying out front-channel logout through FedCM, but that would require a certain level of control over the IdP (support FedCM endpoints) and the RP (integrate with the RP via FedCM and support front-channel logout via FedCM).

cc @samuelgoto

**Comment by michal-tobiasz-wttech** [comment]
Thanks for response. 
My primary intent is to determine if there is a simple solution or plan that can accommodate the scenario I have described.

We are controlling Relying Parties but IdP will not support API that only works for one browser. Also FedCM sounds as a bigger change in our environment regarding a way to only clean cookies on front channel logout.

Do you have other rehomendations?

**Comment by shuranhuang** [comment]
I'd like to ask some questions to get a clearer picture for your use case:

If I understand your use case correctly, before your plan of change, all the sites are on the same domains, i.e.  a.example.com, b.example.com, c.example.com ... and they all rely on idp.example.com for logging in. When a user logs out from a.example.com, the page would navigate to the idp.example.com, which embeds a hidden iframe that sends a SAML logout requests (that clear log in cookies) to a.example.com as well as other sites, so that logging out from one site also logs the user out from other sites. Is this description accurate?

And the plan is to have sites on different domains other than example.com, i.e. now there will be example-a.com. example-b.com, example-c.com ... and example-idp.com - how many sites will there be in total?

**Comment by michal-tobiasz-wttech** [comment]
The description is almost perfect, with one difference: the iframe will not send a logout request to the site that triggered the logout (a.example.com). The rest of the description is accurate.

Regarding the number of sites, there could be up to about 10 different domains involved.

**Comment by samdutton** [comment]
@johannhof — any further follow-up here?

**Comment by johannhof** [comment]
No updates at this point from me - Front-Channel Logout is still a challenging issue with third-party cookies blocked, and finding a good solution (interoperable nonetheless!) will take time.

**Comment by samdutton** [comment]
Thanks @johannhof. 

@michal-tobiasz-wttech I'll close this, as there haven't been any further comments for >8 months, but feel free to reopen.
