### ISSUE TITLE
Long-Term Support for CookiesAllowedForUrls Enterprise Policy 

### ISSUE THREAD

**Issue by bretticus-mc** [privacysandbox/privacy-sandbox-dev-support#312]
Hello,

Does Chrome plan to support the [CookiesAllowedForUrls](https://chromeenterprise.google/policies/?policy=CookiesAllowedForUrls) Enterprise Policy indefinitely? We are planning to tell our customers the the CookiesAllowedForUrls Enterprise Policy is one of the ways they can continue to use our application with third-party cookies. Just want to make sure that Chrome is planning to support this long-term.

**Comment by krgovind** [comment]
@bretticus-mc We currently do not have a deprecation plan for CookiesAllowedForUrls in mind; so you are welcome to provide that guidance. However, we would highly recommend that you consider [migrating your application](https://developers.google.com/privacy-sandbox/3pcd) to third-party cookie replacement APIs/solutions since they have better privacy and security properties, and will work outside of managed environments. Hope that helps!
