### ISSUE TITLE
Iframe with same eTDL+1 as current url context.

### ISSUE THREAD

**Issue by ukaj808** [privacysandbox/privacy-sandbox-dev-support#384]
Hello!

Im testing out third party cookie deprecation via icognito and I noticed something...

I have one website iframed into another: website.sub.domain.com iframed inside sub.domain.com. 

I notice that website.sub.domain.com is still able to read/write its own cookies even though third-party cookies are disabled? 

This might be the expected behavior since they both have the same eTDL+1 (domain.com?); But I cant find any documentation that states this as en exception.

Fiz

**Comment by cfredric** [comment]
This is expected behavior in Chrome (and other browsers), as long as there are no intermediate iframes with a different eTLD+1 (i.e. no "middle" cross-site iframe). Since cookies are scoped to the eTLD+1 (not the origin, for example), there is no privacy boundary between different origins of the same eTLD+1.

Re: documentation, there's an [ongoing effort](https://github.com/explainers-by-googlers/standardizing-cross-site-cookie-semantics) to standardize and document third-party-cookie-blocking behavior between browsers, but right now, that behavior is not standardized.
