### ISSUE TITLE
Hi @jaissam10,

### ISSUE THREAD

**Issue by av1934413** [privacysandbox/privacy-sandbox-dev-support#419]
Hi @jaissam10,

I'm not sure I fully understand your scenario, but the general solution when partitioned cookies/storage are not an option is to use unpartitioned storage, e.g. unpartitioned cookies. Your React app can use the [Storage Access API](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API) to request access to that data.

_Originally posted by @cfredric in https://github.com/privacysandbox/privacy-sandbox-dev-support/issues/409#issuecomment-2310395649_

**Comment by jaissam10** [comment]
@av1934413  There are two issues here. 
First, the StorageAccessAPI will trigger a dialog for the user, which in my case would occur for every new domain's PDF. This isn't an ideal solution since we can't show a popup for every PDF. 
Secondly, this method can only be triggered through an actual user click.

 Let me know if there's another approach.
